/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import {
  DescriptionSnippet,
  LongBylineText,
  NavigationEndpoint,
  ShortBylineText,
  subscribeButton,
  SubscriberCountText,
  SubscriptionButton,
  Thumbnail,
  Title,
  VideoCountText,
} from './index.js';

export interface Channel {
  channelId: string;
  descriptionSnippet: DescriptionSnippet;
  longBylineText: LongBylineText;
  navigationEndpoint: NavigationEndpoint;
  shortBylineText: ShortBylineText;
  subscribeButton: subscribeButton;
  subscriberCountText: SubscriberCountText;
  subscriptionButton: SubscriptionButton;
  thumbnail: Thumbnail;
  title: Title;
  trackingParams: string;
  videoCountText: VideoCountText;
}
