/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import {
  DescriptionSnippet,
  LongBylineText,
  NavigationEndpoint,
  OwnerBadges,
  ShortBylineText,
  subscribeButton,
  SubscriberCountText,
  SubscriptionButton,
  Thumbnail,
  VideoCountText,
} from './index.js';

export interface Channel {
  channelId: string;
  descriptionSnippet?: DescriptionSnippet;
  longBylineText: LongBylineText;
  navigationEndpoint: NavigationEndpoint;
  ownerBadges?: OwnerBadges;
  shortBylineText: ShortBylineText;
  subscribeButton: subscribeButton;
  subscriberCountText?: SubscriberCountText;
  subscriptionButton: SubscriptionButton;
  thumbnail: Thumbnail;
  title: ChannelTitle;
  trackingParams: string;
  videoCountText: VideoCountText;
}

export interface ChannelTitle {
  simpleText: string;
}

export type ownerBadges = unknown[];
