/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { CommandMetadata, NavigationEndpoint } from './shared.js';
import { Channel } from './channel.js';
import { Playlist } from './playlist.js';
import { Video } from './video.js';

export interface ChipCloudChipRenderer {
  text: {
    simpleText: string;
  };
}

export interface ContinuationEndpoint {
  clickTrackingParams: string;
  commandMetadata: CommandMetadata;
  continuationCommand: {
    request: string;
    token: string;
  };
}

export interface FeedFilterChipBarRenderer {
  contents: {
    chipCloudChipRenderer: ChipCloudChipRenderer;
  }[];
}

export interface InitialData {
  contents?: InitialDataContents;
  estimatedResults?: string;
  header?: {
    pageHeaderRenderer?: Record<string, never>;
    searchHeaderRenderer?: {
      aboutTheseResultsButton: object;
      chipBar?: object;
      searchFilterButton: object;
      trackingParams: string;
    };
  };
  metadata?: Record<string, never>;
  microformat?: Record<string, never>;
  onResponseReceivedActions?: Record<string, never>[];
  onResponseReceivedCommands?: {
    adsControlFlowOpportunityReceivedCommand?: {
      adSlotAndLayoutMetadata?: object[];
      enablePacfLoggingWeb?: boolean;
      isInitialLoad?: boolean;
      opportunityType?: string;
    };
    appendContinuationItemsAction?: {
      continuationItems: {
        continuationItemRenderer?: {
          continuationEndpoint: ContinuationEndpoint;
          loggingDirectives?: {
            trackingParams: string;
          };
          trigger: string;
        };
        itemSectionRenderer?: ItemSection;
      }[];
      targetId?: string;
    };
    clickTrackingParams: string;
  }[];
  refinements?: string[];
  responseContext: {
    mainAppWebResponseContext: {
      loggedOut: boolean;
      trackingParam: string;
    };
    maxAgeSeconds?: number;
    serviceTrackingParams: {
      params: {
        key: string;
        value: string;
      }[];
      service: string;
    }[];
    webResponseContextExtensionData: {
      hasDecorated: boolean;
      ytConfigData?: {
        rootVisualElementType: number;
        visitorData: string;
      };
    };
  };
  targetId?: string;
  topbar?: object;
  trackingParams: string;
}

export interface InitialDataContents {
  twoColumnBrowseResultsRenderer?: {
    tabs: {
      expandableTabRenderer?: Record<string, never>;
      tabRenderer?: {
        content?: {
          richGridRenderer: {
            contents: {
              adSlotRenderer?: {
                adSlotMetadata: object;
                enablePacfLoggingWeb: boolean;
                fulfillmentContent: object;
                trackingParams: string;
              };
              channelRenderer?: Channel;
              continuationItemRenderer?: {
                continuationEndpoint: ContinuationEndpoint;
                loggingDirectives?: {
                  trackingParams: string;
                };
                trigger: string;
              };
              horizontalCardListRenderer?: object;
              lockupViewModel?: object;
              movieRenderer?: object;
              playlistRenderer?: Playlist;
              radioRenderer?: object;
              reelShelfRenderer?: object;
              richItemRenderer?: object;
              shelfRenderer?: object;
              videoRenderer?: Video;
            }[];
            header: {
              feedFilterChipBarRenderer: FeedFilterChipBarRenderer;
            };
            trackingParams: string;
          };
        };
        endpoint: NavigationEndpoint;
        selected?: boolean;
        title: string;
        trackingParams: string;
      };
    }[];
  };
  twoColumnSearchResultsRenderer?: {
    primaryContents: {
      sectionListRenderer: {
        contents: {
          continuationItemRenderer?: {
            continuationEndpoint: ContinuationEndpoint;
            loggingDirectives?: {
              trackingParams: string;
            };
            trigger: string;
          };
          itemSectionRenderer?: ItemSection;
        }[];
        hideBottomSeparator: boolean;
        subMenu: object;
        targetId: string;
        trackingParams: string;
      };
    };
  };
}

export interface ItemSection {
  contents: {
    adSlotRenderer?: {
      adSlotMetadata: object;
      enablePacfLoggingWeb: boolean;
      fulfillmentContent: object;
      trackingParams: string;
    };
    channelRenderer?: Channel;
    continuationItemRenderer?: {
      continuationEndpoint: ContinuationEndpoint;
      loggingDirectives?: {
        trackingParams: string;
      };
      trigger: string;
    };
    horizontalCardListRenderer?: object;
    lockupViewModel?: object;
    movieRenderer?: object;
    playlistRenderer?: Playlist;
    radioRenderer?: object;
    reelShelfRenderer?: object;
    richItemRenderer?: object;
    shelfRenderer?: object;
    videoRenderer?: Video;
  }[];
  trackingParams: string;
}
