/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { CommandMetadata } from './shared';
import { Channel } from './channel';
import { Playlist } from './playlist';
import { Video } from './video';

export interface InitialData {
  contents: {
    twoColumnSearchResultsRenderer: {
      primaryContents: {
        sectionListRenderer: {
          contents: {
            continuationItemRenderer?: {
              continuationEndpoint: {
                clickTrackingParams: string;
                commandMetadata: CommandMetadata;
                continuationCommand: {
                  request: string;
                  token: string;
                };
              };
              loggingDirectives: {
                trackingParams: string;
              };
              trigger: string;
            };
            itemSectionRenderer?: {
              contents: {
                adSlotRenderer?: {
                  adSlotMetadata: object;
                  enablePacfLoggingWeb: boolean;
                  fulfillmentContent: object;
                  trackingParams: string;
                };
                channelRenderer?: Channel;
                lockupViewModel?: object;
                playlistRenderer?: Playlist;
                radioRenderer?: object;
                reelShelfRenderer?: object;
                shelfRenderer?: object;
                videoRenderer?: Video;
              }[];
              trackingParams: string;
            };
          }[];
          hideBottomSeparator: boolean;
          subMenu: object;
          targetId: string;
          trackingParams: string;
        };
      };
    };
  };
  estimatedResults: string;
  header: {
    searchHeaderRenderer: {
      aboutTheseResultsButton: object;
      chipBar?: object;
      searchFilterButton: object;
      trackingParams: string;
    };
  };
  onResponseReceivedCommands?: {
    adsControlFlowOpportunityReceivedCommand: {
      adSlotAndLayoutMetadata?: object[];
      enablePacfLoggingWeb?: boolean;
      isInitialLoad?: boolean;
      opportunityType: string;
    };
    clickTrackingParams: string;
  }[];
  refinements: string[];
  responseContext: {
    mainAppWebResponseContext: {
      loggedOut: boolean;
      trackingParam: string;
    };
    serviceTrackingParams: {
      params: {
        key: string;
        value: string;
      }[];
      service: string;
    }[];
    webResponseContextExtensionData: {
      hasDecorated: boolean;
      ytConfigData: {
        rootVisualElementType: number;
        visitorData: string;
      };
    };
  };
  targetId: string;
  topbar: object;
  trackingParams: string;
}
