/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Video {
  channelId: string;
  descriptionSnippet: {
    runs: {
      text: string;
    }[];
  };
  longBylineText: {
    runs: {
      navigationEndpoint?: {
        browseEndpoint: {
          browseId: string;
          canonicalBaseUrl: string;
        };
        clickTrackingParams: string;
        commandMetadata: {
          webCommandMetadata: {
            apiUrl: string;
            rootVe: number;
            url: string;
            webPageType: 'WEB_PAGE_TYPE_CHANNEL';
          };
        };
      };
      text: string;
    }[];
  };
  navigationEndpoint: {
    browseEndpoint: {
      browseId: string;
      canonicalBaseUrl: string;
    };
    clickTrackingParams: string;
    commandMetadata: {
      webCommandMetadata: {
        apiUrl: string;
        rootVe: number;
        url: string;
        webPageType: 'WEB_PAGE_TYPE_CHANNEL';
      };
    };
  };
  shortBylineText: {
    runs: {
      navigationEndpoint?: {
        browseEndpoint: {
          browseId: string;
          canonicalBaseUrl: string;
        };
        clickTrackingParams: string;
        commandMetadata: {
          webCommandMetadata: {
            apiUrl: string;
            rootVe: number;
            url: string;
            webPageType: 'WEB_PAGE_TYPE_CHANNEL';
          };
        };
      };
      text: string;
    }[];
  };
  subscribeButton: {
    buttonRenderer: {
      isDisabled: boolean;
      navigationEndpoint: {
        clickTrackingParams: string;
        commandMetadata: {
          webCommandMetadata: {
            rootVe: number;
            url: string;
            webPageType: 'WEB_PAGE_TYPE_UNKNOWN';
          };
        };
        signInEndpoint: {
          continueAction: string;
          nextEndpoint: {
            clickTrackingParams: string;
            commandMetadata: {
              webCommandMetadata: {
                rootVe: number;
                url: string;
                webPageType: 'WEB_PAGE_TYPE_SEARCH';
              };
            };
            searchEndpoint: {
              params: string;
              query: string;
            };
          };
        };
      };
      size: 'SIZE_DEFAULT';
      style: 'STYLE_DESTRUCTIVE';
      text: {
        runs: {
          text: string;
        }[];
      };
      trackingParams: string;
    };
  };
  subscriberCountText: {
    simpleText: string;
  };
  subscriptionButton: {
    subscribed: boolean;
  };
  thumbnail: {
    thumbnails: {
      height: number;
      url: string;
      width: number;
    }[];
  };
  title: {
    simpleText: string;
  };
  trackingParams: string;
  videoCountText: {
    accessibility: {
      accessibilityData: {
        label: string;
      };
    };
    simpleText: string;
  };
}
